"""pigeon_rename.manifest_builder — Generate self-documenting MANIFEST.md per folder.

Each MANIFEST.md is a complete reference for its folder:
  - Format legend so the manifest explains itself
  - File table with seq, lines, status, exports, dependencies, description
  - Folder API section showing the public contract from __init__.py
  - Internal dependency graph between files in the folder
  - Health summary with compliance stats
  - Module signatures with type hints for LLM context
  - Constants & configuration values
  - Code markers (TODO/FIXME/HACK)

The NOTES column is the living part — it starts empty and grows via
manual edits or automated tools. Existing notes are PRESERVED across rebuilds.
"""
import ast
import re
from datetime import datetime, timezone
from pathlib import Path

from pigeon_rename.limits import PIGEON_MAX, PIGEON_RECOMMENDED, is_excluded

SKIP_DIRS = {'.venv', '__pycache__', 'node_modules', '.git',
             '.next', '.pytest_cache', 'compiler_output', 'rollback_logs',
             'audit_backups', 'logs', '.vscode', 'cache', '.pigeon'}

SKIP_FILES = {'__init__.py', 'conftest.py'}

MAX_COMPLIANT = PIGEON_MAX

_LEGEND = (
    '## How to read this manifest\n'
    '\n'
    'This file is **auto-generated** by `pigeon manifest` and describes every\n'
    'Python module in this folder. It is the single source of truth for:\n'
    '- What each file does (Description)\n'
    '- What each file exports (Exports) and depends on (Deps)\n'
    '- Whether the file meets the Pigeon size budget (Status)\n'
    '- Living operator notes that persist across rebuilds (Notes)\n'
    '\n'
    '**Status icons:** '
    '\u2705 \u2264{max} lines | '
    '\u26a0\ufe0f OVER {max}\u2013300 | '
    '\U0001f7e0 WARN 300\u2013500 | '
    '\U0001f534 CRIT >500\n'
    '\n'
    '**Columns:** '
    'Seq = load order \u00b7 Lines = source line count \u00b7 '
    'Exports = public classes/functions \u00b7 Deps = intra-project imports\n'
)


# ── Public API ────────────────────────────────


def build_manifest(folder: Path, root: Path = None) -> str:
    """Generate self-documenting MANIFEST.md content for a single folder."""
    folder = Path(folder)
    root = Path(root) if root else folder.parent
    existing_notes = _parse_existing_notes(folder / 'MANIFEST.md')
    file_records = _scan_folder_rich(folder)
    if not file_records:
        return ''
    try:
        folder_rel = str(folder.relative_to(root)).replace('\\', '/')
    except ValueError:
        folder_rel = folder.name
    purpose = _infer_folder_purpose(folder)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = []

    # Header
    lines.append(f'# MANIFEST \u2014 {folder_rel}')
    lines.append('')
    if purpose:
        lines.append(f'> {purpose}')
        lines.append('')
    lines.append(f'*Auto-generated by Pigeon Code Compilor manifest_builder | {now}*')
    lines.append('')

    # Legend
    lines.append(_LEGEND.format(max=MAX_COMPLIANT))
    lines.append('')

    # File table
    lines.append('## Files')
    lines.append('')
    lines.append('| Seq | File | Lines | Status | Exports | Deps | Description | Notes |')
    lines.append('|-----|------|------:|--------|---------|------|-------------|-------|')
    for rec in file_records:
        status = _status_icon(rec['lines'])
        seq = rec['seq']
        note = existing_notes.get(rec['name'], '')
        exports_str = ', '.join(rec['exports'][:5])
        if len(rec['exports']) > 5:
            exports_str += f' +{len(rec["exports"]) - 5}'
        deps_str = ', '.join(rec['deps'][:4])
        if len(rec['deps']) > 4:
            deps_str += f' +{len(rec["deps"]) - 4}'
        lines.append(
            f'| {seq} | {rec["name"]} | {rec["lines"]} | {status} '
            f'| {exports_str} | {deps_str} | {rec["desc"]} | {note} |'
        )
    lines.append('')

    # Folder API
    api_lines = _build_folder_api(folder)
    if api_lines:
        lines.append('## Folder API')
        lines.append('')
        lines.append('Public symbols re-exported by `__init__.py`:')
        lines.append('')
        lines.extend(api_lines)
        lines.append('')

    # Dependency graph
    graph_lines = _build_dep_graph(file_records, folder)
    if graph_lines:
        lines.append('## Internal Dependencies')
        lines.append('')
        lines.append('```')
        lines.extend(graph_lines)
        lines.append('```')
        lines.append('')

    # Health
    total = len(file_records)
    ok = sum(1 for r in file_records if r['lines'] <= MAX_COMPLIANT)
    over = total - ok
    total_lines = sum(r['lines'] for r in file_records)
    lines.append('## Health')
    lines.append(f'- **Files:** {total} | **Compliant:** {ok}/{total} ({ok / max(total, 1) * 100:.0f}%)')
    lines.append(f'- **Total lines:** {total_lines} | **Target:** \u2264{MAX_COMPLIANT} per file')
    if over:
        lines.append(f'- **Action needed:** {over} file(s) over limit')
    lines.append('')

    # Module signatures
    sig_section = _build_signatures_section(file_records)
    if sig_section:
        lines.append('## Module Signatures')
        lines.append('')
        lines.append('Function and class signatures (type hints included):')
        lines.append('')
        lines.extend(sig_section)
        lines.append('')

    # Constants
    const_section = _build_constants_section(file_records)
    if const_section:
        lines.append('## Constants & Configuration')
        lines.append('')
        lines.extend(const_section)
        lines.append('')

    # Code markers
    marker_section = _build_markers_section(file_records)
    if marker_section:
        lines.append('## Code Markers')
        lines.append('')
        lines.extend(marker_section)
        lines.append('')

    return '\n'.join(lines)


def build_all_manifests(root: Path, dry_run: bool = False) -> list[dict]:
    """Build MANIFEST.md for every folder that has .py files.

    Returns list of {folder, files, wrote} dicts.
    """
    root = Path(root)
    results = []
    seen = set()
    for py in sorted(root.rglob('*.py')):
        if _should_skip(py, root):
            continue
        folder = py.parent
        if folder in seen:
            continue
        seen.add(folder)
        content = build_manifest(folder, root)
        if not content:
            continue
        files_in = content.count('\n|') - 1
        result = {'folder': str(folder.relative_to(root)).replace('\\', '/'),
                  'files': max(files_in, 0)}
        if not dry_run:
            (folder / 'MANIFEST.md').write_text(content, encoding='utf-8')
            result['wrote'] = True
        else:
            result['wrote'] = False
        results.append(result)
    return results


# ── Folder scanning ──────────────────────────


def _scan_folder_rich(folder: Path) -> list[dict]:
    """Return list of file records with exports, deps, signatures, etc."""
    results = []
    for py in sorted(folder.glob('*.py')):
        if py.name in SKIP_FILES:
            continue
        try:
            text = py.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue
        lc = len(text.splitlines())
        desc = _extract_docstring_first_line(text, py.name)
        exports = _extract_exports(text)
        deps = _extract_deps(text, folder.name)
        seq = _extract_seq(py.name) or f'{len(results) + 1:03d}'
        signatures = _extract_signatures(text)
        classes = _extract_classes(text)
        constants = _extract_constants(text)
        markers = _extract_code_markers(text)
        results.append({
            'name': py.name,
            'lines': lc,
            'desc': desc,
            'exports': exports,
            'deps': deps,
            'seq': seq,
            'signatures': signatures,
            'classes': classes,
            'constants': constants,
            'markers': markers,
        })
    return results


# ── AST extractors ───────────────────────────


def _extract_docstring_first_line(text: str, filename: str) -> str:
    try:
        tree = ast.parse(text)
        ds = ast.get_docstring(tree)
        if ds:
            first = ds.strip().split('\n')[0].strip()
            if ' \u2014 ' in first:
                first = first.split(' \u2014 ', 1)[1].strip()
            elif ' - ' in first:
                parts = first.split(' - ', 1)
                if len(parts[0].split()) <= 4:
                    first = parts[1].strip()
            if len(first) > 80:
                first = first[:77] + '...'
            return first
    except SyntaxError:
        pass
    stem = Path(filename).stem
    clean = re.sub(r'_seq\d+_v\d+', '', stem).replace('_', ' ').strip()
    return clean.capitalize() if clean else filename


def _extract_seq(filename: str) -> str:
    m = re.search(r'_seq(\d+)', filename)
    return m.group(1) if m else ''


def _extract_exports(text: str) -> list[str]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    names = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
            names.append(node.name)
        elif isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
            names.append(f'{node.name}()')
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else ([node.target] if node.target else [])
            for t in targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    names.append(t.id)
    return names


def _extract_deps(text: str, folder_name: str) -> list[str]:
    deps = []
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return deps
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            mod = node.module
            # Track relative imports within project
            if node.level > 0 or '.' in mod:
                leaf = mod.rsplit('.', 1)[-1]
                short = re.sub(r'_seq\d+.*', '', leaf)
                if short and short not in deps:
                    deps.append(short)
    return deps


def _extract_signatures(text: str) -> list[str]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    sigs = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith('_'):
                continue
            sigs.append(_format_signature(node))
        elif isinstance(node, ast.ClassDef):
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if item.name.startswith('_') and item.name != '__init__':
                        continue
                    sigs.append(_format_signature(item, class_name=node.name))
    return sigs


def _format_signature(node, class_name: str = None) -> str:
    prefix = 'async ' if isinstance(node, ast.AsyncFunctionDef) else ''
    params = []
    args = node.args

    defaults_offset = len(args.args) - len(args.defaults)
    for i, arg in enumerate(args.args):
        if arg.arg in ('self', 'cls'):
            continue
        p = arg.arg
        if arg.annotation:
            p += f': {ast.unparse(arg.annotation)}'
        if i >= defaults_offset:
            default = args.defaults[i - defaults_offset]
            try:
                p += f' = {ast.unparse(default)}'
            except Exception:
                p += ' = ...'
        params.append(p)

    if args.vararg:
        p = f'*{args.vararg.arg}'
        if args.vararg.annotation:
            p += f': {ast.unparse(args.vararg.annotation)}'
        params.append(p)
    if args.kwarg:
        p = f'**{args.kwarg.arg}'
        if args.kwarg.annotation:
            p += f': {ast.unparse(args.kwarg.annotation)}'
        params.append(p)

    ret = f' -> {ast.unparse(node.returns)}' if node.returns else ''
    name = f'{class_name}.{node.name}' if class_name else node.name
    return f'{prefix}def {name}({", ".join(params)}){ret}'


def _extract_classes(text: str) -> list[dict]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    classes = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
            bases = [ast.unparse(b) for b in node.bases] if node.bases else []
            decorators = []
            for d in node.decorator_list:
                try:
                    decorators.append(ast.unparse(d))
                except Exception:
                    pass
            methods = [m.name for m in node.body
                       if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))
                       and not m.name.startswith('_')]
            classes.append({
                'name': node.name,
                'bases': bases,
                'decorators': decorators,
                'methods': methods,
                'lines': (node.end_lineno or node.lineno) - node.lineno + 1,
            })
    return classes


def _extract_constants(text: str) -> list[dict]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    consts = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    try:
                        val_str = ast.unparse(node.value)
                        if len(val_str) > 80:
                            val_str = val_str[:77] + '...'
                    except Exception:
                        val_str = '...'
                    consts.append({'name': t.id, 'value': val_str})
    return consts


_MARKER_RE = re.compile(r'#\s*(TODO|FIXME|HACK|XXX|WARN|NOTE)\b', re.IGNORECASE)


def _extract_code_markers(text: str) -> list[dict]:
    markers = []
    for i, line in enumerate(text.splitlines(), 1):
        m = _MARKER_RE.search(line)
        if m:
            tag = m.group(1).upper()
            rest = line[m.end():].strip().lstrip(':').strip()
            if len(rest) > 60:
                rest = rest[:57] + '...'
            markers.append({'tag': tag, 'line': i, 'text': rest})
    return markers


# ── Section builders ─────────────────────────


def _build_signatures_section(file_records: list[dict]) -> list[str]:
    lines = []
    for rec in file_records:
        if not rec['signatures'] and not rec['classes']:
            continue
        short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        lines.append(f'**{short}**')
        lines.append('```python')
        for cls in rec['classes']:
            deco_parts = [f'@{d}' for d in cls['decorators']]
            bases_str = f'({", ".join(cls["bases"])})' if cls['bases'] else ''
            for dp in deco_parts:
                lines.append(dp)
            lines.append(f'class {cls["name"]}{bases_str}:  # {cls["lines"]} lines')
            if cls['methods']:
                lines.append(f'    # methods: {", ".join(cls["methods"])}')
        for sig in rec['signatures']:
            lines.append(sig)
        lines.append('```')
        lines.append('')
    return lines


def _build_constants_section(file_records: list[dict]) -> list[str]:
    all_consts = []
    for rec in file_records:
        for c in rec['constants']:
            short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
            all_consts.append((short, c['name'], c['value']))
    if not all_consts:
        return []
    lines = ['| Module | Constant | Value |',
             '|--------|----------|-------|']
    for mod, name, val in all_consts:
        val_escaped = val.replace('|', '\\|')
        lines.append(f'| {mod} | `{name}` | `{val_escaped}` |')
    return lines


def _build_markers_section(file_records: list[dict]) -> list[str]:
    all_markers = []
    for rec in file_records:
        for m in rec['markers']:
            short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
            all_markers.append((short, m['tag'], m['line'], m['text']))
    if not all_markers:
        return ['*No TODO/FIXME/HACK markers found \u2014 codebase is clean.*']
    lines = ['| Module | Tag | Line | Note |',
             '|--------|-----|-----:|------|']
    for mod, tag, ln, txt in all_markers:
        lines.append(f'| {mod} | {tag} | {ln} | {txt} |')
    return lines


def _build_folder_api(folder: Path) -> list[str]:
    init = folder / '__init__.py'
    if not init.exists():
        return []
    try:
        text = init.read_text(encoding='utf-8', errors='ignore')
        tree = ast.parse(text)
    except Exception:
        return []
    lines = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == '__all__':
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                lines.append(f'- `{elt.value}`')
                    if lines:
                        return lines
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.names:
            for alias in node.names:
                name = alias.asname or alias.name
                if not name.startswith('_'):
                    lines.append(f'- `{name}`')
    return lines


def _build_dep_graph(file_records: list[dict], folder: Path) -> list[str]:
    stem_map = {}
    for rec in file_records:
        short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        stem_map[short] = rec['name']
    graph_lines = []
    for rec in file_records:
        short_name = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        targets = [d for d in rec['deps'] if d in stem_map and d != short_name]
        if targets:
            graph_lines.append(f'{short_name} --> {", ".join(targets)}')
    return graph_lines


# ── Helpers ──────────────────────────────────


def _status_icon(line_count: int) -> str:
    if line_count <= MAX_COMPLIANT:
        return '\u2705'
    elif line_count <= 300:
        return '\u26a0\ufe0f OVER'
    elif line_count <= 500:
        return '\U0001f7e0 WARN'
    else:
        return '\U0001f534 CRIT'


def _infer_folder_purpose(folder: Path) -> str:
    init = folder / '__init__.py'
    if init.exists():
        try:
            text = init.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(text)
            ds = ast.get_docstring(tree)
            if ds:
                return ds.strip().split('\n')[0].strip()
        except Exception:
            pass
    name = folder.name.replace('_', ' ').strip()
    return name.capitalize() if name else ''


def _parse_existing_notes(manifest_path: Path) -> dict:
    notes = {}
    if not manifest_path.exists():
        return notes
    try:
        text = manifest_path.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        return notes
    for line in text.splitlines():
        if not line.startswith('|'):
            continue
        cols = [c.strip() for c in line.split('|')]
        if len(cols) < 8:
            continue
        fname = cols[2]
        if fname.endswith('.py') and cols[-2]:
            notes[fname] = cols[-2]
    return notes


def _should_skip(py: Path, root: Path) -> bool:
    parts = py.relative_to(root).parts
    for p in parts:
        if p in SKIP_DIRS or p.startswith('.venv'):
            return True
    return False
